services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  laravel:
    build: .
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html
    environment:
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 3306
      DB_CONNECTION: mysql
      API_PREFIX: api
      APP_DEBUG: ${APP_DEBUG}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully  

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 30s -i 250ms

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
